config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'teams/show'

  resources :countries 
  resources :teams do
    resources :comments
  end

  root 'countries#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_attached_file :flag, styles: { medium: "30x30>", thumb: "100x100>" }
  	validates_attachment_content_type :flag, content_type: /\Aimage\/.*\Z/

  	has_many :leagues
  	has_many :teams
end

app/models/league.rb
class League < ActiveRecord::Base
	belongs_to :country
	has_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_attached_file :flag, styles: { medium: "30x30>", thumb: "100x100>" }
  	validates_attachment_content_type :flag, content_type: /\Aimage\/.*\Z/

  	has_attached_file :fans, styles: { medium: "500x280>", thumb: "100x100>" }, default_url: "/tipball/images/:style/missing.png"
    validates_attachment_content_type :fans, content_type: /\Aimage\/.*\Z/

    has_attached_file :facilities1, styles: { medium: "500x280>", thumb: "100x100>" }, default_url: "/tipball/images/:style/missing.png"
    validates_attachment_content_type :facilities1, content_type: /\Aimage\/.*\Z/

    has_attached_file :facilities2, styles: { medium: "500x280>", thumb: "100x100>" }, default_url: "/tipball/images/:style/missing.png"
    validates_attachment_content_type :facilities2, content_type: /\Aimage\/.*\Z/

	belongs_to :league
	belongs_to :country

  has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_team
	before_action :find_comment, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

	def index
	end

	def new
		@comment = Comment.new

	end

	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.team_id = @team.id

		if @comment.save
			redirect_to @team, notice: "Hellz Yea Chappy! New Comment Added"
		else
			render 'new', notice: "Awwwh Shit"
		end
	end


	def show
	end

	def edit
	end

	def update
		if @comment.update comment_params
			redirect_to @team, notice: "comment was saved"
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to @team
	end




	private

	def comment_params
		params.require(:comment).permit(:text)
	end

	def find_comment
		@comment = Comment.find(params[:id])
	end

	def find_team
		@team = Team.find(params[:team_id])
	end


end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	before_action :find_country, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

    def home
  		@countries = Country.all.order("title ASC")
  		@leagues = League.all
  		@teams = Team.all.order("title ASC")
    end

    def index
   	@countries = Country.all.order("title ASC")
  		@leagues = League.all
  		@teams = Team.all.order("title ASC")
  		render "home"
    end

	def new
		@country = Country.new
	end

	def create
		@country = Country.new country_params

		if @country.save
			redirect_to @country, notice: "Hellz Yea Chappy! New Country Added"
		else
			render 'new', notice: "Awwwh Shit"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @country.update country_params
			redirect_to @country, notice: "country was saved"
		else
			render 'edit'
		end
	end

	def destroy
		@country.destroy
		redirect_to countries_path
	end


	

	private


	def country_params
		params.require(:country).permit(:title, :flag)
	end

	def find_country
		@country = Country.find(params[:id])
	end



end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
 	before_action :find_team, only: [:show, :edit, :update, :destroy]
	#before_action :find_country, only: [ :show, :edit, :update, :destroy]

	def new
		@team = Team.new
	end

	def create
		@team = Team.new team_params

		if @team.save
			redirect_to @team, notice: "Hellz Yea Chappy! New Team Added"
		else
			render 'new', notice: "Awwwh Shit"
		end
	end

	def show
		@countries = Country.all.order("title ASC")
		@leagues = League.all
		@teams = Team.all.order("title ASC")
		#@comments = Comment.all
		@comments = Comment.where(team_id: @team.id).order("created_at DESC")
	end


	def edit
	end

	def update
		if @team.update team_params
			redirect_to @team, notice: "team was saved"
		else
			render 'edit'
		end
	end

	def destroy
		@team.destroy
		redirect_to countries_path
	end

	private

	def team_params
		params.require(:team).permit(:title, :flag, :fans, :facilities1, :facilities2)
	end

	def find_team
		@team = Team.find(params[:id])
	end
	def find_country
		@country = Country.find(params[:id])
	end
	def find_comment
		@comment = Comment.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/comments/_form.html.erb
<%= form_for ([@team, @comment])  do |f| %>
	<% if @comment.errors.any? %>
	<h2><%= pluralize(@comment.errors.count, "error") %> prevent this post from saving:</h2>
	<ul>
		<% @comment.errors.full_messages.each do |msg| %>
		<li> <%= msg %></li>

		<% end %>
	<%end%>
	
	<%= f.label :text%><br>
	<%= f.text_area :text%>

	<br>

	<%= f.submit 'Post Comment'%>

<% end %>

app/views/comments/edit.html.erb
<div style="margin:12px"><%= link_to 'BACK', team_path(@team) %></div>

<div class="comment-container">
<h1>Edit Comment</h1>

<div class="actions"><%= render 'form' %></div>
</div>

app/views/comments/new.html.erb
<div style="margin:12px"><%= link_to 'BACK', team_path(@team) %></div>

<div class="comment-container"><h1>New Comment</h1>

<div class="actions"><%= render 'form' %></div>

</div>

app/views/countries/_form.html.erb
<%= form_for @country, html: { multipart: true } do |f| %>
	<% if @country.errors.any? %>
	<h2><%= pluralize(@country.errors.count, "error") %> prevent this post from saving:</h2>
	<ul>
		<% @country.errors.full_messages.each do |msg| %>
		<li> <%= msg %></li>

		<% end %>
	<%end%>
	<%= f.label :title%><br>
	<%= f.text_area :title%>

	<br>

	<%= f.label :flag%><br>
	<%= f.file_field :flag %>

	<br>

	<%= f.submit %>

<% end %>

app/views/countries/edit.html.erb
<h1>Edit Country</h1>

<%= render 'form' %>

app/views/countries/home.html.erb
<nav class="country-nav">
	<div class="user-actions">
		<% if user_signed_in? %>
		<%= link_to destroy_user_session_path, method: :delete do %><div class="button">Log out</div><%end%>
		<%else%>
		<%= link_to new_user_session_path do %><div class="button">Sign In</div><%end%>
		<%end%>
	</div>
</nav>
<header>
<h1 class="robo">Tip<i class="fa fa-dribbble fa-spin"></i>Ball</h1>
<h2>Research and Rate<br>Professional Basketball Teams</h2>
</header>

<!-- List Teams inside Leagues and Countries-->
<section class="main-list">
	<h3 class="selector-text">Select Country</h3>
	<% @countries.each do |country| %>
	<div class="country-container" >
		<div class="country robo" >
			<%= image_tag country.flag.url(:medium) %><%= country.title %><i class="fa fa-chevron-right"></i>
		</div>
		<div class="leagues-container" >
			<% @leagues.each do |league| %>
				<% if league.country_id == country.id %>
					<div class="league robo" >
						<p><%= league.title %></p>
					</div>
					<div class="teams-container" >
						<% @teams.each do |team| %>
							<% if team.league_id == league.id %>
								<%= link_to team do%>
									<div class="team robo" >
										<i class="fa fa-dribbble"></i><p><%= team.title %></p><i class="fa fa-chevron-right"></i><i class="fa fa-chevron-right"></i>
									</div>
								<% end %>
							<% end %>
						<% end %>
					</div>	
				<% end %>
			<% end %>
		</div>
	</div>
	<% end %>
</section>

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
	$(".country:first").click(function() {
		$(this).toggleClass("lift")
		$(this).siblings(".leagues-container").toggle();
        $(this).children("i").toggleClass("open");
    });

    var $overlay = $("<div class='country-overlay'><span>COMING SOON</span></div>")
        $('div.country:not(:first)').append($overlay);
</script>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form' %>

app/views/countries/show.html.erb
<%= link_to "Back",  controller: "countries", action: "home", id: @country %> <br>
<%= @country.title %>

<br>

<%= link_to "Edit", edit_country_path(@country) %>
<%= link_to "Delete", country_path(@country), method: :delete, data: { confirm: "Are you sure you want to delete this country?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tipball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:500' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/js/swiper.min.js"></script>
  
</head>
<body>
<div class="body-cover">

  <div class="alert-box">
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
  </div>

  <%= yield %>

  
</div>

</body>
</html>